# Generated by Django 5.1.15 on 2026-08-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0003_lab_allowlist_entry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="logscanhit",
            new_name="workers_log_scan_id_2b5456_idx",
            old_name="workers_log_scan_id_7f2a1b_idx",
        ),
        migrations.RenameIndex(
            model_name="logscanhit",
            new_name="workers_log_domain_c6d32d_idx",
            old_name="workers_log_domain_3c9e4d_idx",
        ),
        migrations.AlterField(
            model_name="labloginscan",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("not_attempted", "Not attempted"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
    ]
