# Generated by Django 5.1.15 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0004_rename_workers_log_scan_indexes_and_lab_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="labloginscan",
            name="is_hidden",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
