# Generated by Django 5.1.15 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0005_labloginscan_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="labloginscan",
            name="proxy_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
