# Generated by Django 5.1.15 on 2026-08-21 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0009_githubfinding_match_snippets"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="githubfinding",
            new_name="integration_scan_id_a33802_idx",
            old_name="integratio_scan_id_repo_txt_idx",
        ),
    ]
